imports:
    - { resource: config.yml }

parameters:
    defer_all_emails: "studymarketing@mailinator.com"

doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "localhost"
        dbname:   "studysauce3"
        user:     "study2"
        password: "itekIO^#(1234"

services:
    pdo:
        class: Doctrine\DBAL\Driver\PDOConnection
        arguments:
            - "mysql:host=localhost;port=3306;dbname=studysauce3"
            - "study2"
            - "itekIO^#(1234"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console


