imports:
    - { resource: config.yml }

parameters:
    defer_all_emails: "studymarketing@mailinator.com"
    stripe_api_key: "sk_test_e6FayAX25zDIq2O17blocj2h"
    stripe_public_key: "pk_test_th5VY2bxRUDSJZ1xCcpJ7CNB"


doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "localhost"
        dbname:   "studysauce3"
        user:     "study2"
        password: "itekIO^#(1234"

services:
    pdo:
        class: Doctrine\DBAL\Driver\PDOConnection
        arguments:
            - "mysql:host=localhost;port=3306;dbname=studysauce3"
            - study2
            - itekIO^#(1234
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
