
# AcmeDemoBundle routes (to be removed)
_studysauce:
    resource: "@StudySauceBundle/Resources/config/routing.php"

_admin:
    resource: "@AdminBundle/Resources/config/routing.php"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /redirect
